from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from dotenv import load_dotenv
load_dotenv()
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableParallel


llm = HuggingFaceEndpoint(
    repo_id="deepseek-ai/DeepSeek-V4-Flash",
    # provider="novita",               # explicitly pick a provider that hosts this model
    task="text-generation",
)
model1 = ChatHuggingFace(llm=llm)

model2 = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite")

prompt1 = PromptTemplate(
    template= "Write a simple and detailed summary for following text: \n {text}",
    input_variables=["text"]
)

prompt2 = PromptTemplate(
    template= "Generate 5 short Q&A for the following topic.\n {text}",
    input_variables=["text"]
)

prompt3 = PromptTemplate(
    template="merge the provided notes and quizs into single document. \n notes => {notes} \n quizs => {quizs} ",
    input_variables=['notes', 'quizs']
)

parser = StrOutputParser()

parallel_chain = RunnableParallel({
    "notes": prompt1 | model2 | parser,
    "quizs": prompt2 | model1 | parser 
})

merge_chain = prompt3 | model2 | parser

final_chain = parallel_chain | merge_chain

topic = """
Ultralytics YOLO11#
Link to this sectionOverview#
YOLO11 was released by Ultralytics on September 10, 2024, delivering excellent accuracy, speed, and efficiency. Building upon the impressive advancements of previous YOLO versions, YOLO11 introduces significant improvements in architecture and training methods, making it a versatile choice for a wide range of computer vision tasks. For the latest Ultralytics model with end-to-end NMS-free inference and optimized edge deployment, see YOLO26.

Ultralytics YOLO11 Comparison Plots

Ultralytics YOLO11 🚀 Podcast generated by NotebookLM


Watch: How to Use Ultralytics YOLO11 for Object Detection and Tracking | How to Benchmark | YOLO11 RELEASED🚀
Try on Ultralytics Platform
Explore and run YOLO11 models directly on Ultralytics Platform.

Link to this sectionKey Features#
Enhanced Feature Extraction: YOLO11 employs an improved backbone and neck architecture, which enhances feature extraction capabilities for more precise object detection and complex task performance.
Optimized for Efficiency and Speed: YOLO11 introduces refined architectural designs and optimized training pipelines, delivering faster processing speeds and maintaining an optimal balance between accuracy and performance.
Greater Accuracy with Fewer Parameters: With advancements in model design, YOLO11m achieves a higher mean Average Precision (mAP) on the COCO dataset while using 22% fewer parameters than YOLOv8m, making it computationally efficient without compromising accuracy.
Adaptability Across Environments: YOLO11 can be seamlessly deployed across various environments, including edge devices, cloud platforms, and systems supporting NVIDIA GPUs, ensuring maximum flexibility.
Broad Range of Supported Tasks: Whether it's object detection, instance segmentation, image classification, pose estimation, or oriented object detection (OBB), YOLO11 is designed to cater to a diverse set of computer vision challenges.
Link to this sectionSupported Tasks and Modes#
YOLO11 builds upon the versatile model range established by earlier Ultralytics YOLO releases, offering enhanced support across various computer vision tasks:

Model	Filenames	Task	Inference	Validation	Training	Export
YOLO11	yolo11n.pt yolo11s.pt yolo11m.pt yolo11l.pt yolo11x.pt	Detection	✅	✅	✅	✅
YOLO11-seg	yolo11n-seg.pt yolo11s-seg.pt yolo11m-seg.pt yolo11l-seg.pt yolo11x-seg.pt	Instance Segmentation	✅	✅	✅	✅
YOLO11-pose	yolo11n-pose.pt yolo11s-pose.pt yolo11m-pose.pt yolo11l-pose.pt yolo11x-pose.pt	Pose/Keypoints	✅	✅	✅	✅
YOLO11-obb	yolo11n-obb.pt yolo11s-obb.pt yolo11m-obb.pt yolo11l-obb.pt yolo11x-obb.pt	Oriented Detection	✅	✅	✅	✅
YOLO11-cls	yolo11n-cls.pt yolo11s-cls.pt yolo11m-cls.pt yolo11l-cls.pt yolo11x-cls.pt	Classification	✅	✅	✅	✅
This table provides an overview of the YOLO11 model variants, showcasing their applicability in specific tasks and compatibility with operational modes such as Inference, Validation, Training, and Export. This flexibility makes YOLO11 suitable for a wide range of applications in computer vision, from real-time detection to complex segmentation tasks.

Link to this sectionPerformance Metrics#


Performance
Detection (COCO)
Segmentation (COCO)
Classification (ImageNet)
Pose (COCO)
OBB (DOTAv1)
See Detection Docs for usage examples with these models trained on COCO, which include 80 pretrained classes.

Model	size
(pixels)	mAPval
50-95	Speed
CPU ONNX
(ms)	Speed
T4 TensorRT10
(ms)	params
(M)	FLOPs
(B)
YOLO11n	640	39.5	56.1 ± 0.8	1.5 ± 0.0	2.6	6.5
YOLO11s	640	47.0	90.0 ± 1.2	2.5 ± 0.0	9.4	21.5
YOLO11m	640	51.5	183.2 ± 2.0	4.7 ± 0.1	20.1	68.0
YOLO11l	640	53.4	238.6 ± 1.4	6.2 ± 0.1	25.3	86.9
YOLO11x	640	54.7	462.8 ± 6.7	11.3 ± 0.2	56.9	194.9
Link to this sectionUsage Examples#
This section provides simple YOLO11 training and inference examples. For full documentation on these and other modes, see the Predict, Train, Val, and Export docs pages.

Note that the example below is for YOLO11 Detect models for object detection. For additional supported tasks, see the Segment, Classify, OBB, and Pose docs.

Example
Python
CLI
PyTorch pretrained *.pt models as well as configuration *.yaml files can be passed to the YOLO() class to create a model instance in Python:


from ultralytics import YOLO

# Load a COCO-pretrained YOLO11n model
model = YOLO("yolo11n.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="coco8.yaml", epochs=100, imgsz=640)

# Run inference with the YOLO11n model on the 'bus.jpg' image
results = model("path/to/bus.jpg")
Link to this sectionCitations and Acknowledgments#
Ultralytics YOLO11 Publication
Ultralytics has not published a formal research paper for YOLO11 due to the rapidly evolving nature of the models. We focus on advancing the technology and making it easier to use, rather than producing static documentation. For the most up-to-date information on YOLO architecture, features, and usage, please refer to our GitHub repository and documentation.

If you use YOLO11 or any other software from this repository in your work, please cite it using the following format:

Quote
BibTeX

@software{yolo11_ultralytics,
  author = {Glenn Jocher and Jing Qiu},
  title = {Ultralytics YOLO11},
  version = {11.0.0},
  year = {2024},
  url = {https://github.com/ultralytics/ultralytics},
  orcid = {0000-0001-5950-6979, 0000-0003-3783-7069},
  license = {AGPL-3.0}
}
Please note that the DOI is pending and will be added to the citation once it is available. YOLO11 models are provided under AGPL-3.0 and Enterprise licenses.

Link to this sectionFAQ#
Link to this sectionWhat are the key improvements in Ultralytics YOLO11 compared to YOLOv8?#
Ultralytics YOLO11 introduces several significant advancements over YOLOv8. Key improvements include:

Enhanced Feature Extraction: YOLO11 employs an improved backbone and neck architecture, enhancing feature extraction capabilities for more precise object detection.
Optimized Efficiency and Speed: Refined architectural designs and optimized training pipelines deliver faster processing speeds while maintaining a balance between accuracy and performance.
Greater Accuracy with Fewer Parameters: YOLO11m achieves higher mean Average Precision (mAP) on the COCO dataset with 22% fewer parameters than YOLOv8m, making it computationally efficient without compromising accuracy.
Adaptability Across Environments: YOLO11 can be deployed across various environments, including edge devices, cloud platforms, and systems supporting NVIDIA GPUs.
Broad Range of Supported Tasks: YOLO11 supports diverse computer vision tasks such as object detection, instance segmentation, image classification, pose estimation, and oriented object detection (OBB).
Link to this sectionHow do I train a YOLO11 model for object detection?#
Training a YOLO11 model for object detection can be done using Python or CLI commands. Below are examples for both methods:

Example
Python
CLI

from ultralytics import YOLO

# Load a COCO-pretrained YOLO11n model
model = YOLO("yolo11n.pt")

# Train the model on the COCO8 example dataset for 100 epochs
results = model.train(data="coco8.yaml", epochs=100, imgsz=640)
For more detailed instructions, refer to the Train documentation.

Link to this sectionWhat tasks can YOLO11 models perform?#
YOLO11 models are versatile and support a wide range of computer vision tasks, including:

Object Detection: Identifying and locating objects within an image.
Instance Segmentation: Detecting objects and delineating their boundaries.
Image Classification: Categorizing images into predefined classes.
Pose Estimation: Detecting and tracking keypoints on human bodies.
Oriented Object Detection (OBB): Detecting objects with rotation for higher precision.
For more information on each task, see the Detection, Instance Segmentation, Classification, Pose Estimation, and Oriented Detection documentation.

Link to this sectionHow does YOLO11 achieve greater accuracy with fewer parameters?#
YOLO11 achieves greater accuracy with fewer parameters through advancements in model design and optimization techniques. The improved architecture allows for efficient feature extraction and processing, resulting in higher mean Average Precision (mAP) on datasets like COCO while using 22% fewer parameters than YOLOv8m. This makes YOLO11 computationally efficient without compromising on accuracy, making it suitable for deployment on resource-constrained devices.

Link to this sectionCan YOLO11 be deployed on edge devices?#
Yes, YOLO11 is designed for adaptability across various environments, including edge devices. Its optimized architecture and efficient processing capabilities make it suitable for deployment on edge devices, cloud platforms, and systems supporting NVIDIA GPUs. This flexibility ensures that YOLO11 can be used in diverse applications, from real-time detection on mobile devices to complex segmentation tasks in cloud environments. For more details on deployment options, refer to the Export documentation.
"""

result = final_chain.invoke({"text": topic})

print(result)

final_chain.get_graph().print_ascii()